/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterPublisherRouteImport } from './routes/register.publisher'
import { Route as PublisherDashboardRouteImport } from './routes/publisher.dashboard'
import { Route as InfluencerDashboardRouteImport } from './routes/influencer.dashboard'
import { Route as AdvertiserDashboardRouteImport } from './routes/advertiser.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as PublisherDashboardIndexRouteImport } from './routes/publisher.dashboard.index'
import { Route as PublisherDashboardSettingsRouteImport } from './routes/publisher.dashboard.settings'
import { Route as PublisherDashboardProfileRouteImport } from './routes/publisher.dashboard.profile'
import { Route as PublisherDashboardApiRouteImport } from './routes/publisher.dashboard.api'
import { Route as PublisherDashboardReportsLeadsRouteImport } from './routes/publisher.dashboard.reports.leads'
import { Route as PublisherDashboardReportsConversionsRouteImport } from './routes/publisher.dashboard.reports.conversions'
import { Route as PublisherDashboardReportsClicksRouteImport } from './routes/publisher.dashboard.reports.clicks'
import { Route as PublisherDashboardPostbackLogsRouteImport } from './routes/publisher.dashboard.postback.logs'
import { Route as PublisherDashboardPostbackIpWhitelistRouteImport } from './routes/publisher.dashboard.postback.ip-whitelist'
import { Route as PublisherDashboardPostbackGlobalRouteImport } from './routes/publisher.dashboard.postback.global'
import { Route as PublisherDashboardPaymentTotalPayoutRouteImport } from './routes/publisher.dashboard.payment.total-payout'
import { Route as PublisherDashboardPaymentPendingPayoutRouteImport } from './routes/publisher.dashboard.payment.pending-payout'
import { Route as PublisherDashboardPaymentInvoiceRouteImport } from './routes/publisher.dashboard.payment.invoice'
import { Route as PublisherDashboardCampaignsAllRouteImport } from './routes/publisher.dashboard.campaigns.all'
import { Route as PublisherDashboardCampaignsActiveRouteImport } from './routes/publisher.dashboard.campaigns.active'
import { Route as PublisherDashboardCampaignsSlugRouteImport } from './routes/publisher.dashboard.campaigns.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPublisherRoute = RegisterPublisherRouteImport.update({
  id: '/register/publisher',
  path: '/register/publisher',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherDashboardRoute = PublisherDashboardRouteImport.update({
  id: '/publisher/dashboard',
  path: '/publisher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerDashboardRoute = InfluencerDashboardRouteImport.update({
  id: '/influencer/dashboard',
  path: '/influencer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserDashboardRoute = AdvertiserDashboardRouteImport.update({
  id: '/advertiser/dashboard',
  path: '/advertiser/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherDashboardIndexRoute = PublisherDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublisherDashboardRoute,
} as any)
const PublisherDashboardSettingsRoute =
  PublisherDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardProfileRoute =
  PublisherDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardApiRoute = PublisherDashboardApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => PublisherDashboardRoute,
} as any)
const PublisherDashboardReportsLeadsRoute =
  PublisherDashboardReportsLeadsRouteImport.update({
    id: '/reports/leads',
    path: '/reports/leads',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardReportsConversionsRoute =
  PublisherDashboardReportsConversionsRouteImport.update({
    id: '/reports/conversions',
    path: '/reports/conversions',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardReportsClicksRoute =
  PublisherDashboardReportsClicksRouteImport.update({
    id: '/reports/clicks',
    path: '/reports/clicks',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPostbackLogsRoute =
  PublisherDashboardPostbackLogsRouteImport.update({
    id: '/postback/logs',
    path: '/postback/logs',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPostbackIpWhitelistRoute =
  PublisherDashboardPostbackIpWhitelistRouteImport.update({
    id: '/postback/ip-whitelist',
    path: '/postback/ip-whitelist',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPostbackGlobalRoute =
  PublisherDashboardPostbackGlobalRouteImport.update({
    id: '/postback/global',
    path: '/postback/global',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPaymentTotalPayoutRoute =
  PublisherDashboardPaymentTotalPayoutRouteImport.update({
    id: '/payment/total-payout',
    path: '/payment/total-payout',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPaymentPendingPayoutRoute =
  PublisherDashboardPaymentPendingPayoutRouteImport.update({
    id: '/payment/pending-payout',
    path: '/payment/pending-payout',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPaymentInvoiceRoute =
  PublisherDashboardPaymentInvoiceRouteImport.update({
    id: '/payment/invoice',
    path: '/payment/invoice',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardCampaignsAllRoute =
  PublisherDashboardCampaignsAllRouteImport.update({
    id: '/campaigns/all',
    path: '/campaigns/all',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardCampaignsActiveRoute =
  PublisherDashboardCampaignsActiveRouteImport.update({
    id: '/campaigns/active',
    path: '/campaigns/active',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardCampaignsSlugRoute =
  PublisherDashboardCampaignsSlugRouteImport.update({
    id: '/campaigns/$slug',
    path: '/campaigns/$slug',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/advertiser/dashboard': typeof AdvertiserDashboardRoute
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/publisher/dashboard': typeof PublisherDashboardRouteWithChildren
  '/register/publisher': typeof RegisterPublisherRoute
  '/publisher/dashboard/api': typeof PublisherDashboardApiRoute
  '/publisher/dashboard/profile': typeof PublisherDashboardProfileRoute
  '/publisher/dashboard/settings': typeof PublisherDashboardSettingsRoute
  '/publisher/dashboard/': typeof PublisherDashboardIndexRoute
  '/publisher/dashboard/campaigns/$slug': typeof PublisherDashboardCampaignsSlugRoute
  '/publisher/dashboard/campaigns/active': typeof PublisherDashboardCampaignsActiveRoute
  '/publisher/dashboard/campaigns/all': typeof PublisherDashboardCampaignsAllRoute
  '/publisher/dashboard/payment/invoice': typeof PublisherDashboardPaymentInvoiceRoute
  '/publisher/dashboard/payment/pending-payout': typeof PublisherDashboardPaymentPendingPayoutRoute
  '/publisher/dashboard/payment/total-payout': typeof PublisherDashboardPaymentTotalPayoutRoute
  '/publisher/dashboard/postback/global': typeof PublisherDashboardPostbackGlobalRoute
  '/publisher/dashboard/postback/ip-whitelist': typeof PublisherDashboardPostbackIpWhitelistRoute
  '/publisher/dashboard/postback/logs': typeof PublisherDashboardPostbackLogsRoute
  '/publisher/dashboard/reports/clicks': typeof PublisherDashboardReportsClicksRoute
  '/publisher/dashboard/reports/conversions': typeof PublisherDashboardReportsConversionsRoute
  '/publisher/dashboard/reports/leads': typeof PublisherDashboardReportsLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/advertiser/dashboard': typeof AdvertiserDashboardRoute
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/register/publisher': typeof RegisterPublisherRoute
  '/publisher/dashboard/api': typeof PublisherDashboardApiRoute
  '/publisher/dashboard/profile': typeof PublisherDashboardProfileRoute
  '/publisher/dashboard/settings': typeof PublisherDashboardSettingsRoute
  '/publisher/dashboard': typeof PublisherDashboardIndexRoute
  '/publisher/dashboard/campaigns/$slug': typeof PublisherDashboardCampaignsSlugRoute
  '/publisher/dashboard/campaigns/active': typeof PublisherDashboardCampaignsActiveRoute
  '/publisher/dashboard/campaigns/all': typeof PublisherDashboardCampaignsAllRoute
  '/publisher/dashboard/payment/invoice': typeof PublisherDashboardPaymentInvoiceRoute
  '/publisher/dashboard/payment/pending-payout': typeof PublisherDashboardPaymentPendingPayoutRoute
  '/publisher/dashboard/payment/total-payout': typeof PublisherDashboardPaymentTotalPayoutRoute
  '/publisher/dashboard/postback/global': typeof PublisherDashboardPostbackGlobalRoute
  '/publisher/dashboard/postback/ip-whitelist': typeof PublisherDashboardPostbackIpWhitelistRoute
  '/publisher/dashboard/postback/logs': typeof PublisherDashboardPostbackLogsRoute
  '/publisher/dashboard/reports/clicks': typeof PublisherDashboardReportsClicksRoute
  '/publisher/dashboard/reports/conversions': typeof PublisherDashboardReportsConversionsRoute
  '/publisher/dashboard/reports/leads': typeof PublisherDashboardReportsLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/advertiser/dashboard': typeof AdvertiserDashboardRoute
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/publisher/dashboard': typeof PublisherDashboardRouteWithChildren
  '/register/publisher': typeof RegisterPublisherRoute
  '/publisher/dashboard/api': typeof PublisherDashboardApiRoute
  '/publisher/dashboard/profile': typeof PublisherDashboardProfileRoute
  '/publisher/dashboard/settings': typeof PublisherDashboardSettingsRoute
  '/publisher/dashboard/': typeof PublisherDashboardIndexRoute
  '/publisher/dashboard/campaigns/$slug': typeof PublisherDashboardCampaignsSlugRoute
  '/publisher/dashboard/campaigns/active': typeof PublisherDashboardCampaignsActiveRoute
  '/publisher/dashboard/campaigns/all': typeof PublisherDashboardCampaignsAllRoute
  '/publisher/dashboard/payment/invoice': typeof PublisherDashboardPaymentInvoiceRoute
  '/publisher/dashboard/payment/pending-payout': typeof PublisherDashboardPaymentPendingPayoutRoute
  '/publisher/dashboard/payment/total-payout': typeof PublisherDashboardPaymentTotalPayoutRoute
  '/publisher/dashboard/postback/global': typeof PublisherDashboardPostbackGlobalRoute
  '/publisher/dashboard/postback/ip-whitelist': typeof PublisherDashboardPostbackIpWhitelistRoute
  '/publisher/dashboard/postback/logs': typeof PublisherDashboardPostbackLogsRoute
  '/publisher/dashboard/reports/clicks': typeof PublisherDashboardReportsClicksRoute
  '/publisher/dashboard/reports/conversions': typeof PublisherDashboardReportsConversionsRoute
  '/publisher/dashboard/reports/leads': typeof PublisherDashboardReportsLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/advertiser/dashboard'
    | '/influencer/dashboard'
    | '/publisher/dashboard'
    | '/register/publisher'
    | '/publisher/dashboard/api'
    | '/publisher/dashboard/profile'
    | '/publisher/dashboard/settings'
    | '/publisher/dashboard/'
    | '/publisher/dashboard/campaigns/$slug'
    | '/publisher/dashboard/campaigns/active'
    | '/publisher/dashboard/campaigns/all'
    | '/publisher/dashboard/payment/invoice'
    | '/publisher/dashboard/payment/pending-payout'
    | '/publisher/dashboard/payment/total-payout'
    | '/publisher/dashboard/postback/global'
    | '/publisher/dashboard/postback/ip-whitelist'
    | '/publisher/dashboard/postback/logs'
    | '/publisher/dashboard/reports/clicks'
    | '/publisher/dashboard/reports/conversions'
    | '/publisher/dashboard/reports/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/advertiser/dashboard'
    | '/influencer/dashboard'
    | '/register/publisher'
    | '/publisher/dashboard/api'
    | '/publisher/dashboard/profile'
    | '/publisher/dashboard/settings'
    | '/publisher/dashboard'
    | '/publisher/dashboard/campaigns/$slug'
    | '/publisher/dashboard/campaigns/active'
    | '/publisher/dashboard/campaigns/all'
    | '/publisher/dashboard/payment/invoice'
    | '/publisher/dashboard/payment/pending-payout'
    | '/publisher/dashboard/payment/total-payout'
    | '/publisher/dashboard/postback/global'
    | '/publisher/dashboard/postback/ip-whitelist'
    | '/publisher/dashboard/postback/logs'
    | '/publisher/dashboard/reports/clicks'
    | '/publisher/dashboard/reports/conversions'
    | '/publisher/dashboard/reports/leads'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/advertiser/dashboard'
    | '/influencer/dashboard'
    | '/publisher/dashboard'
    | '/register/publisher'
    | '/publisher/dashboard/api'
    | '/publisher/dashboard/profile'
    | '/publisher/dashboard/settings'
    | '/publisher/dashboard/'
    | '/publisher/dashboard/campaigns/$slug'
    | '/publisher/dashboard/campaigns/active'
    | '/publisher/dashboard/campaigns/all'
    | '/publisher/dashboard/payment/invoice'
    | '/publisher/dashboard/payment/pending-payout'
    | '/publisher/dashboard/payment/total-payout'
    | '/publisher/dashboard/postback/global'
    | '/publisher/dashboard/postback/ip-whitelist'
    | '/publisher/dashboard/postback/logs'
    | '/publisher/dashboard/reports/clicks'
    | '/publisher/dashboard/reports/conversions'
    | '/publisher/dashboard/reports/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdvertiserDashboardRoute: typeof AdvertiserDashboardRoute
  InfluencerDashboardRoute: typeof InfluencerDashboardRoute
  PublisherDashboardRoute: typeof PublisherDashboardRouteWithChildren
  RegisterPublisherRoute: typeof RegisterPublisherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/publisher': {
      id: '/register/publisher'
      path: '/register/publisher'
      fullPath: '/register/publisher'
      preLoaderRoute: typeof RegisterPublisherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/dashboard': {
      id: '/publisher/dashboard'
      path: '/publisher/dashboard'
      fullPath: '/publisher/dashboard'
      preLoaderRoute: typeof PublisherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/dashboard': {
      id: '/influencer/dashboard'
      path: '/influencer/dashboard'
      fullPath: '/influencer/dashboard'
      preLoaderRoute: typeof InfluencerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser/dashboard': {
      id: '/advertiser/dashboard'
      path: '/advertiser/dashboard'
      fullPath: '/advertiser/dashboard'
      preLoaderRoute: typeof AdvertiserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/dashboard/': {
      id: '/publisher/dashboard/'
      path: '/'
      fullPath: '/publisher/dashboard/'
      preLoaderRoute: typeof PublisherDashboardIndexRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/settings': {
      id: '/publisher/dashboard/settings'
      path: '/settings'
      fullPath: '/publisher/dashboard/settings'
      preLoaderRoute: typeof PublisherDashboardSettingsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/profile': {
      id: '/publisher/dashboard/profile'
      path: '/profile'
      fullPath: '/publisher/dashboard/profile'
      preLoaderRoute: typeof PublisherDashboardProfileRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/api': {
      id: '/publisher/dashboard/api'
      path: '/api'
      fullPath: '/publisher/dashboard/api'
      preLoaderRoute: typeof PublisherDashboardApiRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/reports/leads': {
      id: '/publisher/dashboard/reports/leads'
      path: '/reports/leads'
      fullPath: '/publisher/dashboard/reports/leads'
      preLoaderRoute: typeof PublisherDashboardReportsLeadsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/reports/conversions': {
      id: '/publisher/dashboard/reports/conversions'
      path: '/reports/conversions'
      fullPath: '/publisher/dashboard/reports/conversions'
      preLoaderRoute: typeof PublisherDashboardReportsConversionsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/reports/clicks': {
      id: '/publisher/dashboard/reports/clicks'
      path: '/reports/clicks'
      fullPath: '/publisher/dashboard/reports/clicks'
      preLoaderRoute: typeof PublisherDashboardReportsClicksRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/postback/logs': {
      id: '/publisher/dashboard/postback/logs'
      path: '/postback/logs'
      fullPath: '/publisher/dashboard/postback/logs'
      preLoaderRoute: typeof PublisherDashboardPostbackLogsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/postback/ip-whitelist': {
      id: '/publisher/dashboard/postback/ip-whitelist'
      path: '/postback/ip-whitelist'
      fullPath: '/publisher/dashboard/postback/ip-whitelist'
      preLoaderRoute: typeof PublisherDashboardPostbackIpWhitelistRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/postback/global': {
      id: '/publisher/dashboard/postback/global'
      path: '/postback/global'
      fullPath: '/publisher/dashboard/postback/global'
      preLoaderRoute: typeof PublisherDashboardPostbackGlobalRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/payment/total-payout': {
      id: '/publisher/dashboard/payment/total-payout'
      path: '/payment/total-payout'
      fullPath: '/publisher/dashboard/payment/total-payout'
      preLoaderRoute: typeof PublisherDashboardPaymentTotalPayoutRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/payment/pending-payout': {
      id: '/publisher/dashboard/payment/pending-payout'
      path: '/payment/pending-payout'
      fullPath: '/publisher/dashboard/payment/pending-payout'
      preLoaderRoute: typeof PublisherDashboardPaymentPendingPayoutRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/payment/invoice': {
      id: '/publisher/dashboard/payment/invoice'
      path: '/payment/invoice'
      fullPath: '/publisher/dashboard/payment/invoice'
      preLoaderRoute: typeof PublisherDashboardPaymentInvoiceRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/campaigns/all': {
      id: '/publisher/dashboard/campaigns/all'
      path: '/campaigns/all'
      fullPath: '/publisher/dashboard/campaigns/all'
      preLoaderRoute: typeof PublisherDashboardCampaignsAllRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/campaigns/active': {
      id: '/publisher/dashboard/campaigns/active'
      path: '/campaigns/active'
      fullPath: '/publisher/dashboard/campaigns/active'
      preLoaderRoute: typeof PublisherDashboardCampaignsActiveRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/campaigns/$slug': {
      id: '/publisher/dashboard/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/publisher/dashboard/campaigns/$slug'
      preLoaderRoute: typeof PublisherDashboardCampaignsSlugRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
  }
}

interface PublisherDashboardRouteChildren {
  PublisherDashboardApiRoute: typeof PublisherDashboardApiRoute
  PublisherDashboardProfileRoute: typeof PublisherDashboardProfileRoute
  PublisherDashboardSettingsRoute: typeof PublisherDashboardSettingsRoute
  PublisherDashboardIndexRoute: typeof PublisherDashboardIndexRoute
  PublisherDashboardCampaignsSlugRoute: typeof PublisherDashboardCampaignsSlugRoute
  PublisherDashboardCampaignsActiveRoute: typeof PublisherDashboardCampaignsActiveRoute
  PublisherDashboardCampaignsAllRoute: typeof PublisherDashboardCampaignsAllRoute
  PublisherDashboardPaymentInvoiceRoute: typeof PublisherDashboardPaymentInvoiceRoute
  PublisherDashboardPaymentPendingPayoutRoute: typeof PublisherDashboardPaymentPendingPayoutRoute
  PublisherDashboardPaymentTotalPayoutRoute: typeof PublisherDashboardPaymentTotalPayoutRoute
  PublisherDashboardPostbackGlobalRoute: typeof PublisherDashboardPostbackGlobalRoute
  PublisherDashboardPostbackIpWhitelistRoute: typeof PublisherDashboardPostbackIpWhitelistRoute
  PublisherDashboardPostbackLogsRoute: typeof PublisherDashboardPostbackLogsRoute
  PublisherDashboardReportsClicksRoute: typeof PublisherDashboardReportsClicksRoute
  PublisherDashboardReportsConversionsRoute: typeof PublisherDashboardReportsConversionsRoute
  PublisherDashboardReportsLeadsRoute: typeof PublisherDashboardReportsLeadsRoute
}

const PublisherDashboardRouteChildren: PublisherDashboardRouteChildren = {
  PublisherDashboardApiRoute: PublisherDashboardApiRoute,
  PublisherDashboardProfileRoute: PublisherDashboardProfileRoute,
  PublisherDashboardSettingsRoute: PublisherDashboardSettingsRoute,
  PublisherDashboardIndexRoute: PublisherDashboardIndexRoute,
  PublisherDashboardCampaignsSlugRoute: PublisherDashboardCampaignsSlugRoute,
  PublisherDashboardCampaignsActiveRoute:
    PublisherDashboardCampaignsActiveRoute,
  PublisherDashboardCampaignsAllRoute: PublisherDashboardCampaignsAllRoute,
  PublisherDashboardPaymentInvoiceRoute: PublisherDashboardPaymentInvoiceRoute,
  PublisherDashboardPaymentPendingPayoutRoute:
    PublisherDashboardPaymentPendingPayoutRoute,
  PublisherDashboardPaymentTotalPayoutRoute:
    PublisherDashboardPaymentTotalPayoutRoute,
  PublisherDashboardPostbackGlobalRoute: PublisherDashboardPostbackGlobalRoute,
  PublisherDashboardPostbackIpWhitelistRoute:
    PublisherDashboardPostbackIpWhitelistRoute,
  PublisherDashboardPostbackLogsRoute: PublisherDashboardPostbackLogsRoute,
  PublisherDashboardReportsClicksRoute: PublisherDashboardReportsClicksRoute,
  PublisherDashboardReportsConversionsRoute:
    PublisherDashboardReportsConversionsRoute,
  PublisherDashboardReportsLeadsRoute: PublisherDashboardReportsLeadsRoute,
}

const PublisherDashboardRouteWithChildren =
  PublisherDashboardRoute._addFileChildren(PublisherDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComingSoonRoute: ComingSoonRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdvertiserDashboardRoute: AdvertiserDashboardRoute,
  InfluencerDashboardRoute: InfluencerDashboardRoute,
  PublisherDashboardRoute: PublisherDashboardRouteWithChildren,
  RegisterPublisherRoute: RegisterPublisherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
