/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentPolicyRouteImport } from './routes/payment-policy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FindMeetingRouteImport } from './routes/find-meeting'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as BookMeetingRouteImport } from './routes/book-meeting'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterPublisherRouteImport } from './routes/register.publisher'
import { Route as PublisherDashboardRouteImport } from './routes/publisher.dashboard'
import { Route as InfluencerDashboardRouteImport } from './routes/influencer.dashboard'
import { Route as AdvertiserDashboardRouteImport } from './routes/advertiser.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as PublisherDashboardIndexRouteImport } from './routes/publisher.dashboard.index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin.dashboard.index'
import { Route as PublisherDashboardSettingsRouteImport } from './routes/publisher.dashboard.settings'
import { Route as PublisherDashboardProfileRouteImport } from './routes/publisher.dashboard.profile'
import { Route as PublisherDashboardApiRouteImport } from './routes/publisher.dashboard.api'
import { Route as AdminDashboardSettingsRouteImport } from './routes/admin.dashboard.settings'
import { Route as AdminDashboardProfileRouteImport } from './routes/admin.dashboard.profile'
import { Route as PublisherDashboardReportsLeadsRouteImport } from './routes/publisher.dashboard.reports.leads'
import { Route as PublisherDashboardReportsConversionsRouteImport } from './routes/publisher.dashboard.reports.conversions'
import { Route as PublisherDashboardReportsClicksRouteImport } from './routes/publisher.dashboard.reports.clicks'
import { Route as PublisherDashboardPostbackLogsRouteImport } from './routes/publisher.dashboard.postback.logs'
import { Route as PublisherDashboardPostbackGlobalRouteImport } from './routes/publisher.dashboard.postback.global'
import { Route as PublisherDashboardPaymentTotalPayoutRouteImport } from './routes/publisher.dashboard.payment.total-payout'
import { Route as PublisherDashboardPaymentPendingPayoutRouteImport } from './routes/publisher.dashboard.payment.pending-payout'
import { Route as PublisherDashboardPaymentInvoiceRouteImport } from './routes/publisher.dashboard.payment.invoice'
import { Route as PublisherDashboardCampaignsAllRouteImport } from './routes/publisher.dashboard.campaigns.all'
import { Route as PublisherDashboardCampaignsActiveRouteImport } from './routes/publisher.dashboard.campaigns.active'
import { Route as PublisherDashboardCampaignsSlugRouteImport } from './routes/publisher.dashboard.campaigns.$slug'
import { Route as AdminDashboardWebhookLogsRouteImport } from './routes/admin.dashboard.webhook.logs'
import { Route as AdminDashboardWebhookEventsRouteImport } from './routes/admin.dashboard.webhook.events'
import { Route as AdminDashboardWebhookEndpointsRouteImport } from './routes/admin.dashboard.webhook.endpoints'
import { Route as AdminDashboardReportsLeadsRouteImport } from './routes/admin.dashboard.reports.leads'
import { Route as AdminDashboardReportsConversionsRouteImport } from './routes/admin.dashboard.reports.conversions'
import { Route as AdminDashboardReportsClicksRouteImport } from './routes/admin.dashboard.reports.clicks'
import { Route as AdminDashboardPublishersSuspendedRouteImport } from './routes/admin.dashboard.publishers.suspended'
import { Route as AdminDashboardPublishersPendingRouteImport } from './routes/admin.dashboard.publishers.pending'
import { Route as AdminDashboardPublishersAllRouteImport } from './routes/admin.dashboard.publishers.all'
import { Route as AdminDashboardPublishersActiveRouteImport } from './routes/admin.dashboard.publishers.active'
import { Route as AdminDashboardPostbackTestRouteImport } from './routes/admin.dashboard.postback.test'
import { Route as AdminDashboardPostbackLogsRouteImport } from './routes/admin.dashboard.postback.logs'
import { Route as AdminDashboardPostbackGlobalRouteImport } from './routes/admin.dashboard.postback.global'
import { Route as AdminDashboardPostbackApiRouteImport } from './routes/admin.dashboard.postback.api'
import { Route as AdminDashboardPaymentPendingRouteImport } from './routes/admin.dashboard.payment.pending'
import { Route as AdminDashboardPaymentPaidRouteImport } from './routes/admin.dashboard.payment.paid'
import { Route as AdminDashboardPaymentHistoryRouteImport } from './routes/admin.dashboard.payment.history'
import { Route as AdminDashboardManagementMeetingsRouteImport } from './routes/admin.dashboard.management.meetings'
import { Route as AdminDashboardManagementEmailRouteImport } from './routes/admin.dashboard.management.email'
import { Route as AdminDashboardEarningRevenueRouteImport } from './routes/admin.dashboard.earning.revenue'
import { Route as AdminDashboardEarningPaidRouteImport } from './routes/admin.dashboard.earning.paid'
import { Route as AdminDashboardEarningNetRouteImport } from './routes/admin.dashboard.earning.net'
import { Route as AdminDashboardCampaignsCreateRouteImport } from './routes/admin.dashboard.campaigns.create'
import { Route as AdminDashboardCampaignsApprovalsRouteImport } from './routes/admin.dashboard.campaigns.approvals'
import { Route as AdminDashboardCampaignsAllRouteImport } from './routes/admin.dashboard.campaigns.all'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPolicyRoute = PaymentPolicyRouteImport.update({
  id: '/payment-policy',
  path: '/payment-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMeetingRoute = FindMeetingRouteImport.update({
  id: '/find-meeting',
  path: '/find-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMeetingRoute = BookMeetingRouteImport.update({
  id: '/book-meeting',
  path: '/book-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPublisherRoute = RegisterPublisherRouteImport.update({
  id: '/register/publisher',
  path: '/register/publisher',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherDashboardRoute = PublisherDashboardRouteImport.update({
  id: '/publisher/dashboard',
  path: '/publisher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerDashboardRoute = InfluencerDashboardRouteImport.update({
  id: '/influencer/dashboard',
  path: '/influencer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserDashboardRoute = AdvertiserDashboardRouteImport.update({
  id: '/advertiser/dashboard',
  path: '/advertiser/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherDashboardIndexRoute = PublisherDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublisherDashboardRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const PublisherDashboardSettingsRoute =
  PublisherDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardProfileRoute =
  PublisherDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardApiRoute = PublisherDashboardApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => PublisherDashboardRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardProfileRoute = AdminDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const PublisherDashboardReportsLeadsRoute =
  PublisherDashboardReportsLeadsRouteImport.update({
    id: '/reports/leads',
    path: '/reports/leads',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardReportsConversionsRoute =
  PublisherDashboardReportsConversionsRouteImport.update({
    id: '/reports/conversions',
    path: '/reports/conversions',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardReportsClicksRoute =
  PublisherDashboardReportsClicksRouteImport.update({
    id: '/reports/clicks',
    path: '/reports/clicks',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPostbackLogsRoute =
  PublisherDashboardPostbackLogsRouteImport.update({
    id: '/postback/logs',
    path: '/postback/logs',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPostbackGlobalRoute =
  PublisherDashboardPostbackGlobalRouteImport.update({
    id: '/postback/global',
    path: '/postback/global',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPaymentTotalPayoutRoute =
  PublisherDashboardPaymentTotalPayoutRouteImport.update({
    id: '/payment/total-payout',
    path: '/payment/total-payout',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPaymentPendingPayoutRoute =
  PublisherDashboardPaymentPendingPayoutRouteImport.update({
    id: '/payment/pending-payout',
    path: '/payment/pending-payout',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardPaymentInvoiceRoute =
  PublisherDashboardPaymentInvoiceRouteImport.update({
    id: '/payment/invoice',
    path: '/payment/invoice',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardCampaignsAllRoute =
  PublisherDashboardCampaignsAllRouteImport.update({
    id: '/campaigns/all',
    path: '/campaigns/all',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardCampaignsActiveRoute =
  PublisherDashboardCampaignsActiveRouteImport.update({
    id: '/campaigns/active',
    path: '/campaigns/active',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const PublisherDashboardCampaignsSlugRoute =
  PublisherDashboardCampaignsSlugRouteImport.update({
    id: '/campaigns/$slug',
    path: '/campaigns/$slug',
    getParentRoute: () => PublisherDashboardRoute,
  } as any)
const AdminDashboardWebhookLogsRoute =
  AdminDashboardWebhookLogsRouteImport.update({
    id: '/webhook/logs',
    path: '/webhook/logs',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardWebhookEventsRoute =
  AdminDashboardWebhookEventsRouteImport.update({
    id: '/webhook/events',
    path: '/webhook/events',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardWebhookEndpointsRoute =
  AdminDashboardWebhookEndpointsRouteImport.update({
    id: '/webhook/endpoints',
    path: '/webhook/endpoints',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardReportsLeadsRoute =
  AdminDashboardReportsLeadsRouteImport.update({
    id: '/reports/leads',
    path: '/reports/leads',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardReportsConversionsRoute =
  AdminDashboardReportsConversionsRouteImport.update({
    id: '/reports/conversions',
    path: '/reports/conversions',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardReportsClicksRoute =
  AdminDashboardReportsClicksRouteImport.update({
    id: '/reports/clicks',
    path: '/reports/clicks',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPublishersSuspendedRoute =
  AdminDashboardPublishersSuspendedRouteImport.update({
    id: '/publishers/suspended',
    path: '/publishers/suspended',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPublishersPendingRoute =
  AdminDashboardPublishersPendingRouteImport.update({
    id: '/publishers/pending',
    path: '/publishers/pending',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPublishersAllRoute =
  AdminDashboardPublishersAllRouteImport.update({
    id: '/publishers/all',
    path: '/publishers/all',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPublishersActiveRoute =
  AdminDashboardPublishersActiveRouteImport.update({
    id: '/publishers/active',
    path: '/publishers/active',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPostbackTestRoute =
  AdminDashboardPostbackTestRouteImport.update({
    id: '/postback/test',
    path: '/postback/test',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPostbackLogsRoute =
  AdminDashboardPostbackLogsRouteImport.update({
    id: '/postback/logs',
    path: '/postback/logs',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPostbackGlobalRoute =
  AdminDashboardPostbackGlobalRouteImport.update({
    id: '/postback/global',
    path: '/postback/global',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPostbackApiRoute =
  AdminDashboardPostbackApiRouteImport.update({
    id: '/postback/api',
    path: '/postback/api',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPaymentPendingRoute =
  AdminDashboardPaymentPendingRouteImport.update({
    id: '/payment/pending',
    path: '/payment/pending',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPaymentPaidRoute =
  AdminDashboardPaymentPaidRouteImport.update({
    id: '/payment/paid',
    path: '/payment/paid',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPaymentHistoryRoute =
  AdminDashboardPaymentHistoryRouteImport.update({
    id: '/payment/history',
    path: '/payment/history',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardManagementMeetingsRoute =
  AdminDashboardManagementMeetingsRouteImport.update({
    id: '/management/meetings',
    path: '/management/meetings',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardManagementEmailRoute =
  AdminDashboardManagementEmailRouteImport.update({
    id: '/management/email',
    path: '/management/email',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardEarningRevenueRoute =
  AdminDashboardEarningRevenueRouteImport.update({
    id: '/earning/revenue',
    path: '/earning/revenue',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardEarningPaidRoute =
  AdminDashboardEarningPaidRouteImport.update({
    id: '/earning/paid',
    path: '/earning/paid',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardEarningNetRoute =
  AdminDashboardEarningNetRouteImport.update({
    id: '/earning/net',
    path: '/earning/net',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCampaignsCreateRoute =
  AdminDashboardCampaignsCreateRouteImport.update({
    id: '/campaigns/create',
    path: '/campaigns/create',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCampaignsApprovalsRoute =
  AdminDashboardCampaignsApprovalsRouteImport.update({
    id: '/campaigns/approvals',
    path: '/campaigns/approvals',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCampaignsAllRoute =
  AdminDashboardCampaignsAllRouteImport.update({
    id: '/campaigns/all',
    path: '/campaigns/all',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-meeting': typeof BookMeetingRoute
  '/coming-soon': typeof ComingSoonRoute
  '/find-meeting': typeof FindMeetingRoute
  '/industries': typeof IndustriesRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/advertiser/dashboard': typeof AdvertiserDashboardRoute
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/publisher/dashboard': typeof PublisherDashboardRouteWithChildren
  '/register/publisher': typeof RegisterPublisherRoute
  '/admin/dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/publisher/dashboard/api': typeof PublisherDashboardApiRoute
  '/publisher/dashboard/profile': typeof PublisherDashboardProfileRoute
  '/publisher/dashboard/settings': typeof PublisherDashboardSettingsRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/publisher/dashboard/': typeof PublisherDashboardIndexRoute
  '/admin/dashboard/campaigns/all': typeof AdminDashboardCampaignsAllRoute
  '/admin/dashboard/campaigns/approvals': typeof AdminDashboardCampaignsApprovalsRoute
  '/admin/dashboard/campaigns/create': typeof AdminDashboardCampaignsCreateRoute
  '/admin/dashboard/earning/net': typeof AdminDashboardEarningNetRoute
  '/admin/dashboard/earning/paid': typeof AdminDashboardEarningPaidRoute
  '/admin/dashboard/earning/revenue': typeof AdminDashboardEarningRevenueRoute
  '/admin/dashboard/management/email': typeof AdminDashboardManagementEmailRoute
  '/admin/dashboard/management/meetings': typeof AdminDashboardManagementMeetingsRoute
  '/admin/dashboard/payment/history': typeof AdminDashboardPaymentHistoryRoute
  '/admin/dashboard/payment/paid': typeof AdminDashboardPaymentPaidRoute
  '/admin/dashboard/payment/pending': typeof AdminDashboardPaymentPendingRoute
  '/admin/dashboard/postback/api': typeof AdminDashboardPostbackApiRoute
  '/admin/dashboard/postback/global': typeof AdminDashboardPostbackGlobalRoute
  '/admin/dashboard/postback/logs': typeof AdminDashboardPostbackLogsRoute
  '/admin/dashboard/postback/test': typeof AdminDashboardPostbackTestRoute
  '/admin/dashboard/publishers/active': typeof AdminDashboardPublishersActiveRoute
  '/admin/dashboard/publishers/all': typeof AdminDashboardPublishersAllRoute
  '/admin/dashboard/publishers/pending': typeof AdminDashboardPublishersPendingRoute
  '/admin/dashboard/publishers/suspended': typeof AdminDashboardPublishersSuspendedRoute
  '/admin/dashboard/reports/clicks': typeof AdminDashboardReportsClicksRoute
  '/admin/dashboard/reports/conversions': typeof AdminDashboardReportsConversionsRoute
  '/admin/dashboard/reports/leads': typeof AdminDashboardReportsLeadsRoute
  '/admin/dashboard/webhook/endpoints': typeof AdminDashboardWebhookEndpointsRoute
  '/admin/dashboard/webhook/events': typeof AdminDashboardWebhookEventsRoute
  '/admin/dashboard/webhook/logs': typeof AdminDashboardWebhookLogsRoute
  '/publisher/dashboard/campaigns/$slug': typeof PublisherDashboardCampaignsSlugRoute
  '/publisher/dashboard/campaigns/active': typeof PublisherDashboardCampaignsActiveRoute
  '/publisher/dashboard/campaigns/all': typeof PublisherDashboardCampaignsAllRoute
  '/publisher/dashboard/payment/invoice': typeof PublisherDashboardPaymentInvoiceRoute
  '/publisher/dashboard/payment/pending-payout': typeof PublisherDashboardPaymentPendingPayoutRoute
  '/publisher/dashboard/payment/total-payout': typeof PublisherDashboardPaymentTotalPayoutRoute
  '/publisher/dashboard/postback/global': typeof PublisherDashboardPostbackGlobalRoute
  '/publisher/dashboard/postback/logs': typeof PublisherDashboardPostbackLogsRoute
  '/publisher/dashboard/reports/clicks': typeof PublisherDashboardReportsClicksRoute
  '/publisher/dashboard/reports/conversions': typeof PublisherDashboardReportsConversionsRoute
  '/publisher/dashboard/reports/leads': typeof PublisherDashboardReportsLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-meeting': typeof BookMeetingRoute
  '/coming-soon': typeof ComingSoonRoute
  '/find-meeting': typeof FindMeetingRoute
  '/industries': typeof IndustriesRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/advertiser/dashboard': typeof AdvertiserDashboardRoute
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/register/publisher': typeof RegisterPublisherRoute
  '/admin/dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/publisher/dashboard/api': typeof PublisherDashboardApiRoute
  '/publisher/dashboard/profile': typeof PublisherDashboardProfileRoute
  '/publisher/dashboard/settings': typeof PublisherDashboardSettingsRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/publisher/dashboard': typeof PublisherDashboardIndexRoute
  '/admin/dashboard/campaigns/all': typeof AdminDashboardCampaignsAllRoute
  '/admin/dashboard/campaigns/approvals': typeof AdminDashboardCampaignsApprovalsRoute
  '/admin/dashboard/campaigns/create': typeof AdminDashboardCampaignsCreateRoute
  '/admin/dashboard/earning/net': typeof AdminDashboardEarningNetRoute
  '/admin/dashboard/earning/paid': typeof AdminDashboardEarningPaidRoute
  '/admin/dashboard/earning/revenue': typeof AdminDashboardEarningRevenueRoute
  '/admin/dashboard/management/email': typeof AdminDashboardManagementEmailRoute
  '/admin/dashboard/management/meetings': typeof AdminDashboardManagementMeetingsRoute
  '/admin/dashboard/payment/history': typeof AdminDashboardPaymentHistoryRoute
  '/admin/dashboard/payment/paid': typeof AdminDashboardPaymentPaidRoute
  '/admin/dashboard/payment/pending': typeof AdminDashboardPaymentPendingRoute
  '/admin/dashboard/postback/api': typeof AdminDashboardPostbackApiRoute
  '/admin/dashboard/postback/global': typeof AdminDashboardPostbackGlobalRoute
  '/admin/dashboard/postback/logs': typeof AdminDashboardPostbackLogsRoute
  '/admin/dashboard/postback/test': typeof AdminDashboardPostbackTestRoute
  '/admin/dashboard/publishers/active': typeof AdminDashboardPublishersActiveRoute
  '/admin/dashboard/publishers/all': typeof AdminDashboardPublishersAllRoute
  '/admin/dashboard/publishers/pending': typeof AdminDashboardPublishersPendingRoute
  '/admin/dashboard/publishers/suspended': typeof AdminDashboardPublishersSuspendedRoute
  '/admin/dashboard/reports/clicks': typeof AdminDashboardReportsClicksRoute
  '/admin/dashboard/reports/conversions': typeof AdminDashboardReportsConversionsRoute
  '/admin/dashboard/reports/leads': typeof AdminDashboardReportsLeadsRoute
  '/admin/dashboard/webhook/endpoints': typeof AdminDashboardWebhookEndpointsRoute
  '/admin/dashboard/webhook/events': typeof AdminDashboardWebhookEventsRoute
  '/admin/dashboard/webhook/logs': typeof AdminDashboardWebhookLogsRoute
  '/publisher/dashboard/campaigns/$slug': typeof PublisherDashboardCampaignsSlugRoute
  '/publisher/dashboard/campaigns/active': typeof PublisherDashboardCampaignsActiveRoute
  '/publisher/dashboard/campaigns/all': typeof PublisherDashboardCampaignsAllRoute
  '/publisher/dashboard/payment/invoice': typeof PublisherDashboardPaymentInvoiceRoute
  '/publisher/dashboard/payment/pending-payout': typeof PublisherDashboardPaymentPendingPayoutRoute
  '/publisher/dashboard/payment/total-payout': typeof PublisherDashboardPaymentTotalPayoutRoute
  '/publisher/dashboard/postback/global': typeof PublisherDashboardPostbackGlobalRoute
  '/publisher/dashboard/postback/logs': typeof PublisherDashboardPostbackLogsRoute
  '/publisher/dashboard/reports/clicks': typeof PublisherDashboardReportsClicksRoute
  '/publisher/dashboard/reports/conversions': typeof PublisherDashboardReportsConversionsRoute
  '/publisher/dashboard/reports/leads': typeof PublisherDashboardReportsLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-meeting': typeof BookMeetingRoute
  '/coming-soon': typeof ComingSoonRoute
  '/find-meeting': typeof FindMeetingRoute
  '/industries': typeof IndustriesRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/advertiser/dashboard': typeof AdvertiserDashboardRoute
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/publisher/dashboard': typeof PublisherDashboardRouteWithChildren
  '/register/publisher': typeof RegisterPublisherRoute
  '/admin/dashboard/profile': typeof AdminDashboardProfileRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/publisher/dashboard/api': typeof PublisherDashboardApiRoute
  '/publisher/dashboard/profile': typeof PublisherDashboardProfileRoute
  '/publisher/dashboard/settings': typeof PublisherDashboardSettingsRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/publisher/dashboard/': typeof PublisherDashboardIndexRoute
  '/admin/dashboard/campaigns/all': typeof AdminDashboardCampaignsAllRoute
  '/admin/dashboard/campaigns/approvals': typeof AdminDashboardCampaignsApprovalsRoute
  '/admin/dashboard/campaigns/create': typeof AdminDashboardCampaignsCreateRoute
  '/admin/dashboard/earning/net': typeof AdminDashboardEarningNetRoute
  '/admin/dashboard/earning/paid': typeof AdminDashboardEarningPaidRoute
  '/admin/dashboard/earning/revenue': typeof AdminDashboardEarningRevenueRoute
  '/admin/dashboard/management/email': typeof AdminDashboardManagementEmailRoute
  '/admin/dashboard/management/meetings': typeof AdminDashboardManagementMeetingsRoute
  '/admin/dashboard/payment/history': typeof AdminDashboardPaymentHistoryRoute
  '/admin/dashboard/payment/paid': typeof AdminDashboardPaymentPaidRoute
  '/admin/dashboard/payment/pending': typeof AdminDashboardPaymentPendingRoute
  '/admin/dashboard/postback/api': typeof AdminDashboardPostbackApiRoute
  '/admin/dashboard/postback/global': typeof AdminDashboardPostbackGlobalRoute
  '/admin/dashboard/postback/logs': typeof AdminDashboardPostbackLogsRoute
  '/admin/dashboard/postback/test': typeof AdminDashboardPostbackTestRoute
  '/admin/dashboard/publishers/active': typeof AdminDashboardPublishersActiveRoute
  '/admin/dashboard/publishers/all': typeof AdminDashboardPublishersAllRoute
  '/admin/dashboard/publishers/pending': typeof AdminDashboardPublishersPendingRoute
  '/admin/dashboard/publishers/suspended': typeof AdminDashboardPublishersSuspendedRoute
  '/admin/dashboard/reports/clicks': typeof AdminDashboardReportsClicksRoute
  '/admin/dashboard/reports/conversions': typeof AdminDashboardReportsConversionsRoute
  '/admin/dashboard/reports/leads': typeof AdminDashboardReportsLeadsRoute
  '/admin/dashboard/webhook/endpoints': typeof AdminDashboardWebhookEndpointsRoute
  '/admin/dashboard/webhook/events': typeof AdminDashboardWebhookEventsRoute
  '/admin/dashboard/webhook/logs': typeof AdminDashboardWebhookLogsRoute
  '/publisher/dashboard/campaigns/$slug': typeof PublisherDashboardCampaignsSlugRoute
  '/publisher/dashboard/campaigns/active': typeof PublisherDashboardCampaignsActiveRoute
  '/publisher/dashboard/campaigns/all': typeof PublisherDashboardCampaignsAllRoute
  '/publisher/dashboard/payment/invoice': typeof PublisherDashboardPaymentInvoiceRoute
  '/publisher/dashboard/payment/pending-payout': typeof PublisherDashboardPaymentPendingPayoutRoute
  '/publisher/dashboard/payment/total-payout': typeof PublisherDashboardPaymentTotalPayoutRoute
  '/publisher/dashboard/postback/global': typeof PublisherDashboardPostbackGlobalRoute
  '/publisher/dashboard/postback/logs': typeof PublisherDashboardPostbackLogsRoute
  '/publisher/dashboard/reports/clicks': typeof PublisherDashboardReportsClicksRoute
  '/publisher/dashboard/reports/conversions': typeof PublisherDashboardReportsConversionsRoute
  '/publisher/dashboard/reports/leads': typeof PublisherDashboardReportsLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book-meeting'
    | '/coming-soon'
    | '/find-meeting'
    | '/industries'
    | '/payment-policy'
    | '/privacy'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/advertiser/dashboard'
    | '/influencer/dashboard'
    | '/publisher/dashboard'
    | '/register/publisher'
    | '/admin/dashboard/profile'
    | '/admin/dashboard/settings'
    | '/publisher/dashboard/api'
    | '/publisher/dashboard/profile'
    | '/publisher/dashboard/settings'
    | '/admin/dashboard/'
    | '/publisher/dashboard/'
    | '/admin/dashboard/campaigns/all'
    | '/admin/dashboard/campaigns/approvals'
    | '/admin/dashboard/campaigns/create'
    | '/admin/dashboard/earning/net'
    | '/admin/dashboard/earning/paid'
    | '/admin/dashboard/earning/revenue'
    | '/admin/dashboard/management/email'
    | '/admin/dashboard/management/meetings'
    | '/admin/dashboard/payment/history'
    | '/admin/dashboard/payment/paid'
    | '/admin/dashboard/payment/pending'
    | '/admin/dashboard/postback/api'
    | '/admin/dashboard/postback/global'
    | '/admin/dashboard/postback/logs'
    | '/admin/dashboard/postback/test'
    | '/admin/dashboard/publishers/active'
    | '/admin/dashboard/publishers/all'
    | '/admin/dashboard/publishers/pending'
    | '/admin/dashboard/publishers/suspended'
    | '/admin/dashboard/reports/clicks'
    | '/admin/dashboard/reports/conversions'
    | '/admin/dashboard/reports/leads'
    | '/admin/dashboard/webhook/endpoints'
    | '/admin/dashboard/webhook/events'
    | '/admin/dashboard/webhook/logs'
    | '/publisher/dashboard/campaigns/$slug'
    | '/publisher/dashboard/campaigns/active'
    | '/publisher/dashboard/campaigns/all'
    | '/publisher/dashboard/payment/invoice'
    | '/publisher/dashboard/payment/pending-payout'
    | '/publisher/dashboard/payment/total-payout'
    | '/publisher/dashboard/postback/global'
    | '/publisher/dashboard/postback/logs'
    | '/publisher/dashboard/reports/clicks'
    | '/publisher/dashboard/reports/conversions'
    | '/publisher/dashboard/reports/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book-meeting'
    | '/coming-soon'
    | '/find-meeting'
    | '/industries'
    | '/payment-policy'
    | '/privacy'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/terms'
    | '/advertiser/dashboard'
    | '/influencer/dashboard'
    | '/register/publisher'
    | '/admin/dashboard/profile'
    | '/admin/dashboard/settings'
    | '/publisher/dashboard/api'
    | '/publisher/dashboard/profile'
    | '/publisher/dashboard/settings'
    | '/admin/dashboard'
    | '/publisher/dashboard'
    | '/admin/dashboard/campaigns/all'
    | '/admin/dashboard/campaigns/approvals'
    | '/admin/dashboard/campaigns/create'
    | '/admin/dashboard/earning/net'
    | '/admin/dashboard/earning/paid'
    | '/admin/dashboard/earning/revenue'
    | '/admin/dashboard/management/email'
    | '/admin/dashboard/management/meetings'
    | '/admin/dashboard/payment/history'
    | '/admin/dashboard/payment/paid'
    | '/admin/dashboard/payment/pending'
    | '/admin/dashboard/postback/api'
    | '/admin/dashboard/postback/global'
    | '/admin/dashboard/postback/logs'
    | '/admin/dashboard/postback/test'
    | '/admin/dashboard/publishers/active'
    | '/admin/dashboard/publishers/all'
    | '/admin/dashboard/publishers/pending'
    | '/admin/dashboard/publishers/suspended'
    | '/admin/dashboard/reports/clicks'
    | '/admin/dashboard/reports/conversions'
    | '/admin/dashboard/reports/leads'
    | '/admin/dashboard/webhook/endpoints'
    | '/admin/dashboard/webhook/events'
    | '/admin/dashboard/webhook/logs'
    | '/publisher/dashboard/campaigns/$slug'
    | '/publisher/dashboard/campaigns/active'
    | '/publisher/dashboard/campaigns/all'
    | '/publisher/dashboard/payment/invoice'
    | '/publisher/dashboard/payment/pending-payout'
    | '/publisher/dashboard/payment/total-payout'
    | '/publisher/dashboard/postback/global'
    | '/publisher/dashboard/postback/logs'
    | '/publisher/dashboard/reports/clicks'
    | '/publisher/dashboard/reports/conversions'
    | '/publisher/dashboard/reports/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/book-meeting'
    | '/coming-soon'
    | '/find-meeting'
    | '/industries'
    | '/payment-policy'
    | '/privacy'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/advertiser/dashboard'
    | '/influencer/dashboard'
    | '/publisher/dashboard'
    | '/register/publisher'
    | '/admin/dashboard/profile'
    | '/admin/dashboard/settings'
    | '/publisher/dashboard/api'
    | '/publisher/dashboard/profile'
    | '/publisher/dashboard/settings'
    | '/admin/dashboard/'
    | '/publisher/dashboard/'
    | '/admin/dashboard/campaigns/all'
    | '/admin/dashboard/campaigns/approvals'
    | '/admin/dashboard/campaigns/create'
    | '/admin/dashboard/earning/net'
    | '/admin/dashboard/earning/paid'
    | '/admin/dashboard/earning/revenue'
    | '/admin/dashboard/management/email'
    | '/admin/dashboard/management/meetings'
    | '/admin/dashboard/payment/history'
    | '/admin/dashboard/payment/paid'
    | '/admin/dashboard/payment/pending'
    | '/admin/dashboard/postback/api'
    | '/admin/dashboard/postback/global'
    | '/admin/dashboard/postback/logs'
    | '/admin/dashboard/postback/test'
    | '/admin/dashboard/publishers/active'
    | '/admin/dashboard/publishers/all'
    | '/admin/dashboard/publishers/pending'
    | '/admin/dashboard/publishers/suspended'
    | '/admin/dashboard/reports/clicks'
    | '/admin/dashboard/reports/conversions'
    | '/admin/dashboard/reports/leads'
    | '/admin/dashboard/webhook/endpoints'
    | '/admin/dashboard/webhook/events'
    | '/admin/dashboard/webhook/logs'
    | '/publisher/dashboard/campaigns/$slug'
    | '/publisher/dashboard/campaigns/active'
    | '/publisher/dashboard/campaigns/all'
    | '/publisher/dashboard/payment/invoice'
    | '/publisher/dashboard/payment/pending-payout'
    | '/publisher/dashboard/payment/total-payout'
    | '/publisher/dashboard/postback/global'
    | '/publisher/dashboard/postback/logs'
    | '/publisher/dashboard/reports/clicks'
    | '/publisher/dashboard/reports/conversions'
    | '/publisher/dashboard/reports/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookMeetingRoute: typeof BookMeetingRoute
  ComingSoonRoute: typeof ComingSoonRoute
  FindMeetingRoute: typeof FindMeetingRoute
  IndustriesRoute: typeof IndustriesRoute
  PaymentPolicyRoute: typeof PaymentPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdvertiserDashboardRoute: typeof AdvertiserDashboardRoute
  InfluencerDashboardRoute: typeof InfluencerDashboardRoute
  PublisherDashboardRoute: typeof PublisherDashboardRouteWithChildren
  RegisterPublisherRoute: typeof RegisterPublisherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-policy': {
      id: '/payment-policy'
      path: '/payment-policy'
      fullPath: '/payment-policy'
      preLoaderRoute: typeof PaymentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-meeting': {
      id: '/find-meeting'
      path: '/find-meeting'
      fullPath: '/find-meeting'
      preLoaderRoute: typeof FindMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-meeting': {
      id: '/book-meeting'
      path: '/book-meeting'
      fullPath: '/book-meeting'
      preLoaderRoute: typeof BookMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/publisher': {
      id: '/register/publisher'
      path: '/register/publisher'
      fullPath: '/register/publisher'
      preLoaderRoute: typeof RegisterPublisherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/dashboard': {
      id: '/publisher/dashboard'
      path: '/publisher/dashboard'
      fullPath: '/publisher/dashboard'
      preLoaderRoute: typeof PublisherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/dashboard': {
      id: '/influencer/dashboard'
      path: '/influencer/dashboard'
      fullPath: '/influencer/dashboard'
      preLoaderRoute: typeof InfluencerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser/dashboard': {
      id: '/advertiser/dashboard'
      path: '/advertiser/dashboard'
      fullPath: '/advertiser/dashboard'
      preLoaderRoute: typeof AdvertiserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/dashboard/': {
      id: '/publisher/dashboard/'
      path: '/'
      fullPath: '/publisher/dashboard/'
      preLoaderRoute: typeof PublisherDashboardIndexRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/publisher/dashboard/settings': {
      id: '/publisher/dashboard/settings'
      path: '/settings'
      fullPath: '/publisher/dashboard/settings'
      preLoaderRoute: typeof PublisherDashboardSettingsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/profile': {
      id: '/publisher/dashboard/profile'
      path: '/profile'
      fullPath: '/publisher/dashboard/profile'
      preLoaderRoute: typeof PublisherDashboardProfileRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/api': {
      id: '/publisher/dashboard/api'
      path: '/api'
      fullPath: '/publisher/dashboard/api'
      preLoaderRoute: typeof PublisherDashboardApiRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/admin/dashboard/settings': {
      id: '/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/profile': {
      id: '/admin/dashboard/profile'
      path: '/profile'
      fullPath: '/admin/dashboard/profile'
      preLoaderRoute: typeof AdminDashboardProfileRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/publisher/dashboard/reports/leads': {
      id: '/publisher/dashboard/reports/leads'
      path: '/reports/leads'
      fullPath: '/publisher/dashboard/reports/leads'
      preLoaderRoute: typeof PublisherDashboardReportsLeadsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/reports/conversions': {
      id: '/publisher/dashboard/reports/conversions'
      path: '/reports/conversions'
      fullPath: '/publisher/dashboard/reports/conversions'
      preLoaderRoute: typeof PublisherDashboardReportsConversionsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/reports/clicks': {
      id: '/publisher/dashboard/reports/clicks'
      path: '/reports/clicks'
      fullPath: '/publisher/dashboard/reports/clicks'
      preLoaderRoute: typeof PublisherDashboardReportsClicksRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/postback/logs': {
      id: '/publisher/dashboard/postback/logs'
      path: '/postback/logs'
      fullPath: '/publisher/dashboard/postback/logs'
      preLoaderRoute: typeof PublisherDashboardPostbackLogsRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/postback/global': {
      id: '/publisher/dashboard/postback/global'
      path: '/postback/global'
      fullPath: '/publisher/dashboard/postback/global'
      preLoaderRoute: typeof PublisherDashboardPostbackGlobalRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/payment/total-payout': {
      id: '/publisher/dashboard/payment/total-payout'
      path: '/payment/total-payout'
      fullPath: '/publisher/dashboard/payment/total-payout'
      preLoaderRoute: typeof PublisherDashboardPaymentTotalPayoutRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/payment/pending-payout': {
      id: '/publisher/dashboard/payment/pending-payout'
      path: '/payment/pending-payout'
      fullPath: '/publisher/dashboard/payment/pending-payout'
      preLoaderRoute: typeof PublisherDashboardPaymentPendingPayoutRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/payment/invoice': {
      id: '/publisher/dashboard/payment/invoice'
      path: '/payment/invoice'
      fullPath: '/publisher/dashboard/payment/invoice'
      preLoaderRoute: typeof PublisherDashboardPaymentInvoiceRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/campaigns/all': {
      id: '/publisher/dashboard/campaigns/all'
      path: '/campaigns/all'
      fullPath: '/publisher/dashboard/campaigns/all'
      preLoaderRoute: typeof PublisherDashboardCampaignsAllRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/campaigns/active': {
      id: '/publisher/dashboard/campaigns/active'
      path: '/campaigns/active'
      fullPath: '/publisher/dashboard/campaigns/active'
      preLoaderRoute: typeof PublisherDashboardCampaignsActiveRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/publisher/dashboard/campaigns/$slug': {
      id: '/publisher/dashboard/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/publisher/dashboard/campaigns/$slug'
      preLoaderRoute: typeof PublisherDashboardCampaignsSlugRouteImport
      parentRoute: typeof PublisherDashboardRoute
    }
    '/admin/dashboard/webhook/logs': {
      id: '/admin/dashboard/webhook/logs'
      path: '/webhook/logs'
      fullPath: '/admin/dashboard/webhook/logs'
      preLoaderRoute: typeof AdminDashboardWebhookLogsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/webhook/events': {
      id: '/admin/dashboard/webhook/events'
      path: '/webhook/events'
      fullPath: '/admin/dashboard/webhook/events'
      preLoaderRoute: typeof AdminDashboardWebhookEventsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/webhook/endpoints': {
      id: '/admin/dashboard/webhook/endpoints'
      path: '/webhook/endpoints'
      fullPath: '/admin/dashboard/webhook/endpoints'
      preLoaderRoute: typeof AdminDashboardWebhookEndpointsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/reports/leads': {
      id: '/admin/dashboard/reports/leads'
      path: '/reports/leads'
      fullPath: '/admin/dashboard/reports/leads'
      preLoaderRoute: typeof AdminDashboardReportsLeadsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/reports/conversions': {
      id: '/admin/dashboard/reports/conversions'
      path: '/reports/conversions'
      fullPath: '/admin/dashboard/reports/conversions'
      preLoaderRoute: typeof AdminDashboardReportsConversionsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/reports/clicks': {
      id: '/admin/dashboard/reports/clicks'
      path: '/reports/clicks'
      fullPath: '/admin/dashboard/reports/clicks'
      preLoaderRoute: typeof AdminDashboardReportsClicksRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/publishers/suspended': {
      id: '/admin/dashboard/publishers/suspended'
      path: '/publishers/suspended'
      fullPath: '/admin/dashboard/publishers/suspended'
      preLoaderRoute: typeof AdminDashboardPublishersSuspendedRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/publishers/pending': {
      id: '/admin/dashboard/publishers/pending'
      path: '/publishers/pending'
      fullPath: '/admin/dashboard/publishers/pending'
      preLoaderRoute: typeof AdminDashboardPublishersPendingRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/publishers/all': {
      id: '/admin/dashboard/publishers/all'
      path: '/publishers/all'
      fullPath: '/admin/dashboard/publishers/all'
      preLoaderRoute: typeof AdminDashboardPublishersAllRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/publishers/active': {
      id: '/admin/dashboard/publishers/active'
      path: '/publishers/active'
      fullPath: '/admin/dashboard/publishers/active'
      preLoaderRoute: typeof AdminDashboardPublishersActiveRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/postback/test': {
      id: '/admin/dashboard/postback/test'
      path: '/postback/test'
      fullPath: '/admin/dashboard/postback/test'
      preLoaderRoute: typeof AdminDashboardPostbackTestRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/postback/logs': {
      id: '/admin/dashboard/postback/logs'
      path: '/postback/logs'
      fullPath: '/admin/dashboard/postback/logs'
      preLoaderRoute: typeof AdminDashboardPostbackLogsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/postback/global': {
      id: '/admin/dashboard/postback/global'
      path: '/postback/global'
      fullPath: '/admin/dashboard/postback/global'
      preLoaderRoute: typeof AdminDashboardPostbackGlobalRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/postback/api': {
      id: '/admin/dashboard/postback/api'
      path: '/postback/api'
      fullPath: '/admin/dashboard/postback/api'
      preLoaderRoute: typeof AdminDashboardPostbackApiRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/payment/pending': {
      id: '/admin/dashboard/payment/pending'
      path: '/payment/pending'
      fullPath: '/admin/dashboard/payment/pending'
      preLoaderRoute: typeof AdminDashboardPaymentPendingRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/payment/paid': {
      id: '/admin/dashboard/payment/paid'
      path: '/payment/paid'
      fullPath: '/admin/dashboard/payment/paid'
      preLoaderRoute: typeof AdminDashboardPaymentPaidRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/payment/history': {
      id: '/admin/dashboard/payment/history'
      path: '/payment/history'
      fullPath: '/admin/dashboard/payment/history'
      preLoaderRoute: typeof AdminDashboardPaymentHistoryRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/management/meetings': {
      id: '/admin/dashboard/management/meetings'
      path: '/management/meetings'
      fullPath: '/admin/dashboard/management/meetings'
      preLoaderRoute: typeof AdminDashboardManagementMeetingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/management/email': {
      id: '/admin/dashboard/management/email'
      path: '/management/email'
      fullPath: '/admin/dashboard/management/email'
      preLoaderRoute: typeof AdminDashboardManagementEmailRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/earning/revenue': {
      id: '/admin/dashboard/earning/revenue'
      path: '/earning/revenue'
      fullPath: '/admin/dashboard/earning/revenue'
      preLoaderRoute: typeof AdminDashboardEarningRevenueRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/earning/paid': {
      id: '/admin/dashboard/earning/paid'
      path: '/earning/paid'
      fullPath: '/admin/dashboard/earning/paid'
      preLoaderRoute: typeof AdminDashboardEarningPaidRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/earning/net': {
      id: '/admin/dashboard/earning/net'
      path: '/earning/net'
      fullPath: '/admin/dashboard/earning/net'
      preLoaderRoute: typeof AdminDashboardEarningNetRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/campaigns/create': {
      id: '/admin/dashboard/campaigns/create'
      path: '/campaigns/create'
      fullPath: '/admin/dashboard/campaigns/create'
      preLoaderRoute: typeof AdminDashboardCampaignsCreateRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/campaigns/approvals': {
      id: '/admin/dashboard/campaigns/approvals'
      path: '/campaigns/approvals'
      fullPath: '/admin/dashboard/campaigns/approvals'
      preLoaderRoute: typeof AdminDashboardCampaignsApprovalsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/campaigns/all': {
      id: '/admin/dashboard/campaigns/all'
      path: '/campaigns/all'
      fullPath: '/admin/dashboard/campaigns/all'
      preLoaderRoute: typeof AdminDashboardCampaignsAllRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardProfileRoute: typeof AdminDashboardProfileRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardCampaignsAllRoute: typeof AdminDashboardCampaignsAllRoute
  AdminDashboardCampaignsApprovalsRoute: typeof AdminDashboardCampaignsApprovalsRoute
  AdminDashboardCampaignsCreateRoute: typeof AdminDashboardCampaignsCreateRoute
  AdminDashboardEarningNetRoute: typeof AdminDashboardEarningNetRoute
  AdminDashboardEarningPaidRoute: typeof AdminDashboardEarningPaidRoute
  AdminDashboardEarningRevenueRoute: typeof AdminDashboardEarningRevenueRoute
  AdminDashboardManagementEmailRoute: typeof AdminDashboardManagementEmailRoute
  AdminDashboardManagementMeetingsRoute: typeof AdminDashboardManagementMeetingsRoute
  AdminDashboardPaymentHistoryRoute: typeof AdminDashboardPaymentHistoryRoute
  AdminDashboardPaymentPaidRoute: typeof AdminDashboardPaymentPaidRoute
  AdminDashboardPaymentPendingRoute: typeof AdminDashboardPaymentPendingRoute
  AdminDashboardPostbackApiRoute: typeof AdminDashboardPostbackApiRoute
  AdminDashboardPostbackGlobalRoute: typeof AdminDashboardPostbackGlobalRoute
  AdminDashboardPostbackLogsRoute: typeof AdminDashboardPostbackLogsRoute
  AdminDashboardPostbackTestRoute: typeof AdminDashboardPostbackTestRoute
  AdminDashboardPublishersActiveRoute: typeof AdminDashboardPublishersActiveRoute
  AdminDashboardPublishersAllRoute: typeof AdminDashboardPublishersAllRoute
  AdminDashboardPublishersPendingRoute: typeof AdminDashboardPublishersPendingRoute
  AdminDashboardPublishersSuspendedRoute: typeof AdminDashboardPublishersSuspendedRoute
  AdminDashboardReportsClicksRoute: typeof AdminDashboardReportsClicksRoute
  AdminDashboardReportsConversionsRoute: typeof AdminDashboardReportsConversionsRoute
  AdminDashboardReportsLeadsRoute: typeof AdminDashboardReportsLeadsRoute
  AdminDashboardWebhookEndpointsRoute: typeof AdminDashboardWebhookEndpointsRoute
  AdminDashboardWebhookEventsRoute: typeof AdminDashboardWebhookEventsRoute
  AdminDashboardWebhookLogsRoute: typeof AdminDashboardWebhookLogsRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardProfileRoute: AdminDashboardProfileRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardCampaignsAllRoute: AdminDashboardCampaignsAllRoute,
  AdminDashboardCampaignsApprovalsRoute: AdminDashboardCampaignsApprovalsRoute,
  AdminDashboardCampaignsCreateRoute: AdminDashboardCampaignsCreateRoute,
  AdminDashboardEarningNetRoute: AdminDashboardEarningNetRoute,
  AdminDashboardEarningPaidRoute: AdminDashboardEarningPaidRoute,
  AdminDashboardEarningRevenueRoute: AdminDashboardEarningRevenueRoute,
  AdminDashboardManagementEmailRoute: AdminDashboardManagementEmailRoute,
  AdminDashboardManagementMeetingsRoute: AdminDashboardManagementMeetingsRoute,
  AdminDashboardPaymentHistoryRoute: AdminDashboardPaymentHistoryRoute,
  AdminDashboardPaymentPaidRoute: AdminDashboardPaymentPaidRoute,
  AdminDashboardPaymentPendingRoute: AdminDashboardPaymentPendingRoute,
  AdminDashboardPostbackApiRoute: AdminDashboardPostbackApiRoute,
  AdminDashboardPostbackGlobalRoute: AdminDashboardPostbackGlobalRoute,
  AdminDashboardPostbackLogsRoute: AdminDashboardPostbackLogsRoute,
  AdminDashboardPostbackTestRoute: AdminDashboardPostbackTestRoute,
  AdminDashboardPublishersActiveRoute: AdminDashboardPublishersActiveRoute,
  AdminDashboardPublishersAllRoute: AdminDashboardPublishersAllRoute,
  AdminDashboardPublishersPendingRoute: AdminDashboardPublishersPendingRoute,
  AdminDashboardPublishersSuspendedRoute:
    AdminDashboardPublishersSuspendedRoute,
  AdminDashboardReportsClicksRoute: AdminDashboardReportsClicksRoute,
  AdminDashboardReportsConversionsRoute: AdminDashboardReportsConversionsRoute,
  AdminDashboardReportsLeadsRoute: AdminDashboardReportsLeadsRoute,
  AdminDashboardWebhookEndpointsRoute: AdminDashboardWebhookEndpointsRoute,
  AdminDashboardWebhookEventsRoute: AdminDashboardWebhookEventsRoute,
  AdminDashboardWebhookLogsRoute: AdminDashboardWebhookLogsRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface PublisherDashboardRouteChildren {
  PublisherDashboardApiRoute: typeof PublisherDashboardApiRoute
  PublisherDashboardProfileRoute: typeof PublisherDashboardProfileRoute
  PublisherDashboardSettingsRoute: typeof PublisherDashboardSettingsRoute
  PublisherDashboardIndexRoute: typeof PublisherDashboardIndexRoute
  PublisherDashboardCampaignsSlugRoute: typeof PublisherDashboardCampaignsSlugRoute
  PublisherDashboardCampaignsActiveRoute: typeof PublisherDashboardCampaignsActiveRoute
  PublisherDashboardCampaignsAllRoute: typeof PublisherDashboardCampaignsAllRoute
  PublisherDashboardPaymentInvoiceRoute: typeof PublisherDashboardPaymentInvoiceRoute
  PublisherDashboardPaymentPendingPayoutRoute: typeof PublisherDashboardPaymentPendingPayoutRoute
  PublisherDashboardPaymentTotalPayoutRoute: typeof PublisherDashboardPaymentTotalPayoutRoute
  PublisherDashboardPostbackGlobalRoute: typeof PublisherDashboardPostbackGlobalRoute
  PublisherDashboardPostbackLogsRoute: typeof PublisherDashboardPostbackLogsRoute
  PublisherDashboardReportsClicksRoute: typeof PublisherDashboardReportsClicksRoute
  PublisherDashboardReportsConversionsRoute: typeof PublisherDashboardReportsConversionsRoute
  PublisherDashboardReportsLeadsRoute: typeof PublisherDashboardReportsLeadsRoute
}

const PublisherDashboardRouteChildren: PublisherDashboardRouteChildren = {
  PublisherDashboardApiRoute: PublisherDashboardApiRoute,
  PublisherDashboardProfileRoute: PublisherDashboardProfileRoute,
  PublisherDashboardSettingsRoute: PublisherDashboardSettingsRoute,
  PublisherDashboardIndexRoute: PublisherDashboardIndexRoute,
  PublisherDashboardCampaignsSlugRoute: PublisherDashboardCampaignsSlugRoute,
  PublisherDashboardCampaignsActiveRoute:
    PublisherDashboardCampaignsActiveRoute,
  PublisherDashboardCampaignsAllRoute: PublisherDashboardCampaignsAllRoute,
  PublisherDashboardPaymentInvoiceRoute: PublisherDashboardPaymentInvoiceRoute,
  PublisherDashboardPaymentPendingPayoutRoute:
    PublisherDashboardPaymentPendingPayoutRoute,
  PublisherDashboardPaymentTotalPayoutRoute:
    PublisherDashboardPaymentTotalPayoutRoute,
  PublisherDashboardPostbackGlobalRoute: PublisherDashboardPostbackGlobalRoute,
  PublisherDashboardPostbackLogsRoute: PublisherDashboardPostbackLogsRoute,
  PublisherDashboardReportsClicksRoute: PublisherDashboardReportsClicksRoute,
  PublisherDashboardReportsConversionsRoute:
    PublisherDashboardReportsConversionsRoute,
  PublisherDashboardReportsLeadsRoute: PublisherDashboardReportsLeadsRoute,
}

const PublisherDashboardRouteWithChildren =
  PublisherDashboardRoute._addFileChildren(PublisherDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookMeetingRoute: BookMeetingRoute,
  ComingSoonRoute: ComingSoonRoute,
  FindMeetingRoute: FindMeetingRoute,
  IndustriesRoute: IndustriesRoute,
  PaymentPolicyRoute: PaymentPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdvertiserDashboardRoute: AdvertiserDashboardRoute,
  InfluencerDashboardRoute: InfluencerDashboardRoute,
  PublisherDashboardRoute: PublisherDashboardRouteWithChildren,
  RegisterPublisherRoute: RegisterPublisherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
