/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as RegisterPublisherRouteImport } from './routes/register.publisher'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardApiRouteImport } from './routes/dashboard.api'
import { Route as DashboardReportsLeadsRouteImport } from './routes/dashboard.reports.leads'
import { Route as DashboardReportsConversionsRouteImport } from './routes/dashboard.reports.conversions'
import { Route as DashboardReportsClicksRouteImport } from './routes/dashboard.reports.clicks'
import { Route as DashboardPostbackLogsRouteImport } from './routes/dashboard.postback.logs'
import { Route as DashboardPostbackIpWhitelistRouteImport } from './routes/dashboard.postback.ip-whitelist'
import { Route as DashboardPostbackGlobalRouteImport } from './routes/dashboard.postback.global'
import { Route as DashboardPaymentTotalPayoutRouteImport } from './routes/dashboard.payment.total-payout'
import { Route as DashboardPaymentPendingPayoutRouteImport } from './routes/dashboard.payment.pending-payout'
import { Route as DashboardPaymentInvoiceRouteImport } from './routes/dashboard.payment.invoice'
import { Route as DashboardCampaignsAllRouteImport } from './routes/dashboard.campaigns.all'
import { Route as DashboardCampaignsActiveRouteImport } from './routes/dashboard.campaigns.active'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const RegisterPublisherRoute = RegisterPublisherRouteImport.update({
  id: '/register/publisher',
  path: '/register/publisher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiRoute = DashboardApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsLeadsRoute = DashboardReportsLeadsRouteImport.update({
  id: '/reports/leads',
  path: '/reports/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsConversionsRoute =
  DashboardReportsConversionsRouteImport.update({
    id: '/reports/conversions',
    path: '/reports/conversions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsClicksRoute = DashboardReportsClicksRouteImport.update({
  id: '/reports/clicks',
  path: '/reports/clicks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostbackLogsRoute = DashboardPostbackLogsRouteImport.update({
  id: '/postback/logs',
  path: '/postback/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostbackIpWhitelistRoute =
  DashboardPostbackIpWhitelistRouteImport.update({
    id: '/postback/ip-whitelist',
    path: '/postback/ip-whitelist',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPostbackGlobalRoute = DashboardPostbackGlobalRouteImport.update({
  id: '/postback/global',
  path: '/postback/global',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentTotalPayoutRoute =
  DashboardPaymentTotalPayoutRouteImport.update({
    id: '/payment/total-payout',
    path: '/payment/total-payout',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPaymentPendingPayoutRoute =
  DashboardPaymentPendingPayoutRouteImport.update({
    id: '/payment/pending-payout',
    path: '/payment/pending-payout',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPaymentInvoiceRoute = DashboardPaymentInvoiceRouteImport.update({
  id: '/payment/invoice',
  path: '/payment/invoice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsAllRoute = DashboardCampaignsAllRouteImport.update({
  id: '/campaigns/all',
  path: '/campaigns/all',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsActiveRoute =
  DashboardCampaignsActiveRouteImport.update({
    id: '/campaigns/active',
    path: '/campaigns/active',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/register/publisher': typeof RegisterPublisherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/active': typeof DashboardCampaignsActiveRoute
  '/dashboard/campaigns/all': typeof DashboardCampaignsAllRoute
  '/dashboard/payment/invoice': typeof DashboardPaymentInvoiceRoute
  '/dashboard/payment/pending-payout': typeof DashboardPaymentPendingPayoutRoute
  '/dashboard/payment/total-payout': typeof DashboardPaymentTotalPayoutRoute
  '/dashboard/postback/global': typeof DashboardPostbackGlobalRoute
  '/dashboard/postback/ip-whitelist': typeof DashboardPostbackIpWhitelistRoute
  '/dashboard/postback/logs': typeof DashboardPostbackLogsRoute
  '/dashboard/reports/clicks': typeof DashboardReportsClicksRoute
  '/dashboard/reports/conversions': typeof DashboardReportsConversionsRoute
  '/dashboard/reports/leads': typeof DashboardReportsLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/register/publisher': typeof RegisterPublisherRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/campaigns/active': typeof DashboardCampaignsActiveRoute
  '/dashboard/campaigns/all': typeof DashboardCampaignsAllRoute
  '/dashboard/payment/invoice': typeof DashboardPaymentInvoiceRoute
  '/dashboard/payment/pending-payout': typeof DashboardPaymentPendingPayoutRoute
  '/dashboard/payment/total-payout': typeof DashboardPaymentTotalPayoutRoute
  '/dashboard/postback/global': typeof DashboardPostbackGlobalRoute
  '/dashboard/postback/ip-whitelist': typeof DashboardPostbackIpWhitelistRoute
  '/dashboard/postback/logs': typeof DashboardPostbackLogsRoute
  '/dashboard/reports/clicks': typeof DashboardReportsClicksRoute
  '/dashboard/reports/conversions': typeof DashboardReportsConversionsRoute
  '/dashboard/reports/leads': typeof DashboardReportsLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/register/publisher': typeof RegisterPublisherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/active': typeof DashboardCampaignsActiveRoute
  '/dashboard/campaigns/all': typeof DashboardCampaignsAllRoute
  '/dashboard/payment/invoice': typeof DashboardPaymentInvoiceRoute
  '/dashboard/payment/pending-payout': typeof DashboardPaymentPendingPayoutRoute
  '/dashboard/payment/total-payout': typeof DashboardPaymentTotalPayoutRoute
  '/dashboard/postback/global': typeof DashboardPostbackGlobalRoute
  '/dashboard/postback/ip-whitelist': typeof DashboardPostbackIpWhitelistRoute
  '/dashboard/postback/logs': typeof DashboardPostbackLogsRoute
  '/dashboard/reports/clicks': typeof DashboardReportsClicksRoute
  '/dashboard/reports/conversions': typeof DashboardReportsConversionsRoute
  '/dashboard/reports/leads': typeof DashboardReportsLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/dashboard'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/dashboard/api'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/register/publisher'
    | '/dashboard/'
    | '/dashboard/campaigns/active'
    | '/dashboard/campaigns/all'
    | '/dashboard/payment/invoice'
    | '/dashboard/payment/pending-payout'
    | '/dashboard/payment/total-payout'
    | '/dashboard/postback/global'
    | '/dashboard/postback/ip-whitelist'
    | '/dashboard/postback/logs'
    | '/dashboard/reports/clicks'
    | '/dashboard/reports/conversions'
    | '/dashboard/reports/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/dashboard/api'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/register/publisher'
    | '/dashboard'
    | '/dashboard/campaigns/active'
    | '/dashboard/campaigns/all'
    | '/dashboard/payment/invoice'
    | '/dashboard/payment/pending-payout'
    | '/dashboard/payment/total-payout'
    | '/dashboard/postback/global'
    | '/dashboard/postback/ip-whitelist'
    | '/dashboard/postback/logs'
    | '/dashboard/reports/clicks'
    | '/dashboard/reports/conversions'
    | '/dashboard/reports/leads'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/dashboard'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/dashboard/api'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/register/publisher'
    | '/dashboard/'
    | '/dashboard/campaigns/active'
    | '/dashboard/campaigns/all'
    | '/dashboard/payment/invoice'
    | '/dashboard/payment/pending-payout'
    | '/dashboard/payment/total-payout'
    | '/dashboard/postback/global'
    | '/dashboard/postback/ip-whitelist'
    | '/dashboard/postback/logs'
    | '/dashboard/reports/clicks'
    | '/dashboard/reports/conversions'
    | '/dashboard/reports/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RegisterPublisherRoute: typeof RegisterPublisherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/register/publisher': {
      id: '/register/publisher'
      path: '/register/publisher'
      fullPath: '/register/publisher'
      preLoaderRoute: typeof RegisterPublisherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api': {
      id: '/dashboard/api'
      path: '/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof DashboardApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/leads': {
      id: '/dashboard/reports/leads'
      path: '/reports/leads'
      fullPath: '/dashboard/reports/leads'
      preLoaderRoute: typeof DashboardReportsLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/conversions': {
      id: '/dashboard/reports/conversions'
      path: '/reports/conversions'
      fullPath: '/dashboard/reports/conversions'
      preLoaderRoute: typeof DashboardReportsConversionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/clicks': {
      id: '/dashboard/reports/clicks'
      path: '/reports/clicks'
      fullPath: '/dashboard/reports/clicks'
      preLoaderRoute: typeof DashboardReportsClicksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/postback/logs': {
      id: '/dashboard/postback/logs'
      path: '/postback/logs'
      fullPath: '/dashboard/postback/logs'
      preLoaderRoute: typeof DashboardPostbackLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/postback/ip-whitelist': {
      id: '/dashboard/postback/ip-whitelist'
      path: '/postback/ip-whitelist'
      fullPath: '/dashboard/postback/ip-whitelist'
      preLoaderRoute: typeof DashboardPostbackIpWhitelistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/postback/global': {
      id: '/dashboard/postback/global'
      path: '/postback/global'
      fullPath: '/dashboard/postback/global'
      preLoaderRoute: typeof DashboardPostbackGlobalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment/total-payout': {
      id: '/dashboard/payment/total-payout'
      path: '/payment/total-payout'
      fullPath: '/dashboard/payment/total-payout'
      preLoaderRoute: typeof DashboardPaymentTotalPayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment/pending-payout': {
      id: '/dashboard/payment/pending-payout'
      path: '/payment/pending-payout'
      fullPath: '/dashboard/payment/pending-payout'
      preLoaderRoute: typeof DashboardPaymentPendingPayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment/invoice': {
      id: '/dashboard/payment/invoice'
      path: '/payment/invoice'
      fullPath: '/dashboard/payment/invoice'
      preLoaderRoute: typeof DashboardPaymentInvoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/all': {
      id: '/dashboard/campaigns/all'
      path: '/campaigns/all'
      fullPath: '/dashboard/campaigns/all'
      preLoaderRoute: typeof DashboardCampaignsAllRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/active': {
      id: '/dashboard/campaigns/active'
      path: '/campaigns/active'
      fullPath: '/dashboard/campaigns/active'
      preLoaderRoute: typeof DashboardCampaignsActiveRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardApiRoute: typeof DashboardApiRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCampaignsActiveRoute: typeof DashboardCampaignsActiveRoute
  DashboardCampaignsAllRoute: typeof DashboardCampaignsAllRoute
  DashboardPaymentInvoiceRoute: typeof DashboardPaymentInvoiceRoute
  DashboardPaymentPendingPayoutRoute: typeof DashboardPaymentPendingPayoutRoute
  DashboardPaymentTotalPayoutRoute: typeof DashboardPaymentTotalPayoutRoute
  DashboardPostbackGlobalRoute: typeof DashboardPostbackGlobalRoute
  DashboardPostbackIpWhitelistRoute: typeof DashboardPostbackIpWhitelistRoute
  DashboardPostbackLogsRoute: typeof DashboardPostbackLogsRoute
  DashboardReportsClicksRoute: typeof DashboardReportsClicksRoute
  DashboardReportsConversionsRoute: typeof DashboardReportsConversionsRoute
  DashboardReportsLeadsRoute: typeof DashboardReportsLeadsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiRoute: DashboardApiRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCampaignsActiveRoute: DashboardCampaignsActiveRoute,
  DashboardCampaignsAllRoute: DashboardCampaignsAllRoute,
  DashboardPaymentInvoiceRoute: DashboardPaymentInvoiceRoute,
  DashboardPaymentPendingPayoutRoute: DashboardPaymentPendingPayoutRoute,
  DashboardPaymentTotalPayoutRoute: DashboardPaymentTotalPayoutRoute,
  DashboardPostbackGlobalRoute: DashboardPostbackGlobalRoute,
  DashboardPostbackIpWhitelistRoute: DashboardPostbackIpWhitelistRoute,
  DashboardPostbackLogsRoute: DashboardPostbackLogsRoute,
  DashboardReportsClicksRoute: DashboardReportsClicksRoute,
  DashboardReportsConversionsRoute: DashboardReportsConversionsRoute,
  DashboardReportsLeadsRoute: DashboardReportsLeadsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComingSoonRoute: ComingSoonRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RegisterPublisherRoute: RegisterPublisherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
